In [ ]:
import numpy as np 
import torch
from sklearn.model_selection import train_test_split

In [2]:
# import glob

In [5]:
# 2. Generate Some Dummy Data (Replace with your actual data)
np.random.seed(42)
X = np.random.rand(100, 10)  # 100 samples, 10 features
y = np.random.randint(0, 2, 100) # Binary labels (0 or 1)
np.unique(y)


array([0, 1], dtype=int32)

In [6]:
# 3. Split Data into Training and Testing Sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Convert to PyTorch Tensors
X_train = torch.tensor(X_train, dtype=torch.float32)
y_train = torch.tensor(y_train, dtype=torch.float32).unsqueeze(1) # Reshape to [batch_size, 1]
X_test = torch.tensor(X_test, dtype=torch.float32)
y_test = torch.tensor(y_test, dtype=torch.float32).unsqueeze(1)

In [8]:
X_train

tensor([[0.5202, 0.8522, 0.5519, 0.5609, 0.8767, 0.4035, 0.1340, 0.0288, 0.7551,
         0.6203],
        [0.2311, 0.6719, 0.0197, 0.1041, 0.7999, 0.1785, 0.6527, 0.2382, 0.0994,
         0.2432],
        [0.6150, 0.9901, 0.1401, 0.5183, 0.8774, 0.7408, 0.6970, 0.7025, 0.3595,
         0.2936],
        [0.7916, 0.7896, 0.0912, 0.4944, 0.0576, 0.5495, 0.4415, 0.8877, 0.3509,
         0.1171],
        [0.3237, 0.4254, 0.5076, 0.2424, 0.1148, 0.6106, 0.2886, 0.5812, 0.1544,
         0.4811],
        [0.9083, 0.2396, 0.1449, 0.4895, 0.9857, 0.2421, 0.6721, 0.7616, 0.2376,
         0.7282],
        [0.1031, 0.9026, 0.5053, 0.8265, 0.3200, 0.8955, 0.3892, 0.0108, 0.9054,
         0.0913],
        [0.0828, 0.6032, 0.2453, 0.3893, 0.2887, 0.3557, 0.7190, 0.2971, 0.5664,
         0.4761],
        [0.1196, 0.7132, 0.7608, 0.5613, 0.7710, 0.4938, 0.5227, 0.4275, 0.0254,
         0.1079],
        [0.9383, 0.1812, 0.0665, 0.7411, 0.5745, 0.8418, 0.1398, 0.7953, 0.2016,
         0.1637],
        [0

In [7]:
y_train

tensor([[0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
      