In [11]:
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
from sklearn.linear_model import LinearRegression
from sklearn.datasets import make_blobs
from sklearn.manifold import TSNE

import numpy as np

In [7]:
# !pip install scikit-learn

In [27]:
data= [1.0,2.0,3.0,4.0]
tens= torch.tensor(data, dtype= torch.float32)
print(tens)
print(tens.dtype)
print(torch.numel(tens)) # caculate the no elements in tensor 
print(torch.is_tensor(tens)) # check if the tensor is pytorch tensor 
print(torch.is_storage(tens)) # check if the tensor is storage object

tensor([1., 2., 3., 4.])
torch.float32
4
True
False


In [32]:
# create 2D tensor 
twod_tensor= torch.randn(4,5)
print(twod_tensor)
print(twod_tensor.shape)

tensor([[-0.0524, -1.5450, -0.8416, -0.1129,  2.6054],
        [-0.6808,  0.1024,  1.2642, -0.4304,  1.0985],
        [ 1.0637, -0.9525,  0.1885, -1.4223,  0.9082],
        [ 1.4314,  1.3149, -1.4689,  0.0597,  0.0546]])
torch.Size([4, 5])


In [37]:
complex_tens= torch.randn(2,4, dtype= torch.complex64)
print(complex_tens)
print(complex_tens.shape)
print(torch.is_complex(complex_tens)) #check if the tensor is complex dtype tensor

tensor([[-0.1180+0.0422j, -0.8695-0.4538j, -0.0198-0.4542j, -0.1506+0.2556j],
        [ 0.8357-0.2877j,  0.2479+0.8276j, -0.7610-1.0618j, -0.1741+1.2067j]])
torch.Size([2, 4])
True


In [43]:
# create the zero tensor 
zeros = torch.zeros(2,4) # crete the zero tensor (given the dimensions)
zeros_like= torch.zeros_like(complex_tens) #create the zero like tensor

print(zeros)
print(zeros_like)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j]])


In [45]:
# create the zero tensor 
ones= torch.ones(2,4) # crete the zero tensor (given the dimensions)
ones_like= torch.ones_like(complex_tens) #create the zero like tensor

print(ones)
print(ones_like)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j],
        [1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j]])


In [46]:
#create the loglike tensor 
log_tens = torch.logspace(start=-10, end=10, steps=5)
print(log_tens)

tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])


In [58]:
#create the torch tensor range between 2 to 4 

ranged_tenst= torch.arange(start=0, end=4, step=1, dtype=torch.float16, requires_grad=True)
print(ranged_tenst)
print(ranged_tenst.shape)
print(ranged_tenst.dtype)


tensor([0., 1., 2., 3.], dtype=torch.float16, requires_grad=True)
torch.Size([4])
torch.float16


In [66]:
# Create the linespace arrays 
ranged_linespace = torch.linspace(start=0, 
                                  end=10, 
                                  steps=5,
                                  dtype=torch.int8) #equally spaced
print(ranged_linespace)
print(ranged_linespace.shape)
print(ranged_linespace.dtype)

tensor([ 0,  2,  5,  7, 10], dtype=torch.int8)
torch.Size([5])
torch.int8


In [68]:
# empty tensors 

empty_tensor= torch.empty(4,5) # create the empty tensor 
print(empty_tensor)
print(empty_tensor.dtype)

tensor([[8.4490e-39, 9.0918e-39, 1.0102e-38, 8.9082e-39, 9.2755e-39],
        [1.0837e-38, 8.4490e-39, 9.2755e-39, 8.7245e-39, 1.0102e-38],
        [8.4490e-39, 9.6429e-39, 8.4490e-39, 9.6429e-39, 9.2755e-39],
        [1.0286e-38, 9.0919e-39, 8.9082e-39, 9.2755e-39, 8.4490e-39]])
torch.float32


In [70]:
# create the tensors having diagonal =1 
dia_ones= torch.eye(4) 
print(dia_ones)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])


In [71]:
# no grad 
torch.no_grad()

In [72]:
torch.enable_grad()

# Quantization

In [83]:
quant_tensor = torch.quantize_per_tensor(torch.tensor([-1.0, 0.0, 1.0, 2.0]), 
                          scale= 0.1, 
                          zero_point=10, 
                          dtype= torch.quint8)
print(quant_tensor)
print(quant_tensor.dtype)

tensor([-1.,  0.,  1.,  2.], size=(4,), dtype=torch.quint8,
       quantization_scheme=torch.per_tensor_affine, scale=0.1, zero_point=10)
torch.quint8


In [81]:
# Dequantize 

dequant_tensor = torch.dequantize(quant_tensor)
print(dequant_tensor)
print(dequant_tensor.dtype)

tensor([-1.,  0.,  1.,  2.])
torch.float32


# Indexing, Slicing, Joining, Mutating Ops

In [91]:
# concatinate the sequences of tensor 

a= torch.randn(2, 3)
b= torch.randn(2, 3)

concatenated= torch.cat((a,b), 0)
print(concatenated)

tensor([[ 0.8421, -0.1233,  0.9259],
        [ 0.6814, -0.2672,  2.3272],
        [-0.8850,  1.9019, -0.5742],
        [-0.8576,  1.1672,  0.6899]])


In [92]:
concatenated= torch.cat((a,b), 1)
print(concatenated)

tensor([[ 0.8421, -0.1233,  0.9259, -0.8850,  1.9019, -0.5742],
        [ 0.6814, -0.2672,  2.3272, -0.8576,  1.1672,  0.6899]])


In [93]:
a= torch.randn(2, 3)
b= torch.randn(2, 3)

concatenated= torch.concatenate((a,b), 0)
print(concatenated)

tensor([[ 0.2142, -0.8857,  2.0158],
        [ 0.4880,  2.0540,  1.5170],
        [-0.3409, -1.8777,  0.0302],
        [ 1.2262, -2.0709,  1.0853]])


In [95]:
# return the index where the Zero is presents 

t = torch.tensor([1, 0, 1])
torch.argwhere(t)

tensor([[0],
        [2]])

In [97]:
torch.stack((a,b))

tensor([[[ 0.2142, -0.8857,  2.0158],
         [ 0.4880,  2.0540,  1.5170]],

        [[-0.3409, -1.8777,  0.0302],
         [ 1.2262, -2.0709,  1.0853]]])

# Random sampling

In [103]:
import torch

torch.manual_seed(1)  # Sets the seed for generating random numbers

# Example usage:
random_tensor = torch.rand(3, 3)
print(random_tensor)


tensor([[0.7576, 0.2793, 0.4031],
        [0.7347, 0.0293, 0.7999],
        [0.3971, 0.7544, 0.5695]])


In [130]:
torch.normal(mean=torch.arange(1., 11.), std=torch.arange(1, 0, -0.1))

tensor([ 1.3036,  1.5436,  2.7648,  4.3905,  5.5570,  6.1106,  7.1546,  7.6926,
         9.0168, 10.1609])

In [131]:
rates = torch.rand(4, 4) * 5
torch.poisson(rates)

tensor([[1., 1., 2., 2.],
        [2., 3., 5., 1.],
        [1., 0., 6., 4.],
        [3., 3., 1., 0.]])

In [133]:
torch.get_num_threads()

4

In [137]:
# Returns a tensor where each row contains num_samples indices sampled from the multinomial 
# (a stricter definition would be multivariate,
weights = torch.tensor([0, 10, 3, 0], dtype=torch.float)

torch.multinomial(weights, 2)

tensor([2, 1])

In [138]:
a = torch.empty(3, 3).uniform_(0, 1)
a

tensor([[0.1958, 0.3045, 0.0882],
        [0.9570, 0.5952, 0.9210],
        [0.5327, 0.7718, 0.3404]])

In [139]:
a.flatten()

tensor([0.1958, 0.3045, 0.0882, 0.9570, 0.5952, 0.9210, 0.5327, 0.7718, 0.3404])

In [140]:
torch.bernoulli(a)

tensor([[1., 0., 0.],
        [1., 1., 1.],
        [0., 1., 1.]])

# Clamping

In [106]:
a = torch.randn(4)
print(a)

clamped_nums= torch.clamp(a, min=-0.5, max=0.5)
print(clamped_nums)

tensor([ 0.2222,  0.5773, -1.7637,  0.2264])
tensor([ 0.2222,  0.5000, -0.5000,  0.2264])


In [108]:
a = torch.randn(4)
print(a)

clamped_nums= torch.clip(a, min=-0.5, max=0.5)
print(clamped_nums)

tensor([-0.1103,  0.2913,  0.5848,  0.2149])
tensor([-0.1103,  0.2913,  0.5000,  0.2149])


In [111]:
# checks if the two tensors are near by matches
a = torch.randn(4)
b = torch.randn(4)

ans= torch.allclose(a,b)
print(ans)

False


In [114]:
a = torch.randn(4)
torch.ge(a, a) #greater

tensor([True, True, True, True])

In [115]:
a = torch.randn(4)
torch.greater(a, a) #greater

tensor([False, False, False, False])

In [123]:
# Returns the k largest elements of the given input tensor along a given dimension.
a= torch.randn(2,4)
print(a)

kth_element= torch.topk(a, k=1,  largest=True)
print(kth_element)

tensor([[-2.2122,  0.0484, -0.0916,  0.1386],
        [-0.6317,  0.3046, -0.3564,  0.7867]])
torch.return_types.topk(
values=tensor([[0.1386],
        [0.7867]]),
indices=tensor([[3],
        [3]]))


In [124]:
x = torch.tensor([0, 1, 2, 3, 4])
torch.save(x, "tensor.pt")